name: CICD Data Process
on:
  repository_dispatch:
    types: [data_process]

concurrency:
  group: cicd_data_process
  cancel-in-progress: false

jobs:
  update_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Download release_json
        if: github.event.client_payload.release_json != ''
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.event.client_payload.release_json }}
          github-token: ${{ secrets.ACCESS_DEVOPS_TOKEN }}
          repository: quantropi/${{ github.event.client_payload.repo }}
          run-id: ${{ github.event.client_payload.id }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Handle incoming data
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_DEVOPS_TOKEN }}
        run: node ${{ github.workspace }}/data_process/data_process.js

      - name: Commit and Push Changes
        run: |
          git config --global user.email "devops-agent@quantropi.com"
          git config --global user.name "quantropi-devops-agent"
          git pull
          git add ./src/data
          git commit -m "Automatically update data via repository_dispatch" || echo "No changes to commit"
          git push origin master

      - name: Trigger deploy github pages
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.ACCESS_DEVOPS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/quantropi/cicd_dashboard/dispatches \
            -d '{
                "event_type": "deoloy_pages",
                "client_payload": {}
            }'